modLoader="javafml"
loaderVersion="${forge_loader_requirement}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/simple-voice-chat/issues"
displayURL="https://modrepo.de/minecraft/voicechat/overview"
logoFile="icon.png"
# credits=""
authors="Max Henkel"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/voicechat.json"
description='''A working voice chat in Minecraft!'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirement}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=false
    versionRange="[${cloth_config_version},)"
    ordering="AFTER"
    side="BOTH"